#!/bin/bash

# Autor:        Antonio Narcilio
# Version:      2.0
# Last update:  Sep 8, 2021 

#  - - - - - - - - - - - - - - - - 

# NOT CHANGE
DIR_INSTALLATION='/opt/vivaldi/resources/vivaldi/style/';
FILE_CSS=common.css;
FILE_BUTTONS_CSS=buttons_macos.css;


# - - - - - - - - MAIN - - - - - - - - 

echo -e "\e[1;30mRun the script as adm/root! \e[0m"
# 🎯 Criando arquivo de backup
cd $DIR_INSTALLATION && cp $FILE_CSS $FILE_CSS.bak;
status=$?;

# 🎯 Verificando o retorno da operação bem ou mal sucedida

# Se mal sucedido
if [ $status -ne 0 ]; then
  echo -e "\e[37;45mThe installation process cannot be completed\e[0m";

# Se bem sucedido
elif [ $status -eq 0 ]; then
  cd ${DIR_INSTALLATION} && cat ${FILE_CSS}.bak ${FILE_BUTTONS_CSS} > ${FILE_CSS};
  # Pegando statudo do retorno da operação 0|1
  status=$?
  # 🎯 Verificando o retorno da operação bem ou mal sucedida
  if [ $status -ne 0 ]; then
    echo -e "\e[1;41mButtons stylization unsuccessful! \e[0m";
  elif [ $status -eq 0 ]; then
    echo -e "\e[30;42mButtons stylization successfully added! \e[0m";
  else
    echo -e "\e[1;31mError no return obtained \e[0m";
  fi

# Se não obtiver nenhum retorno
else
  echo -e "\e[1;31mError no return obtained \e[0m";
fi
